from pydantic import BaseModel, Field, field_validator
from app.schemas.source_understanding import SourceUnderstanding
from app.schemas.content_strategy import ContentStrategy
from app.schemas.content_generation import GeneratedContent


class PipelineRequest(BaseModel):
    """
    Request model for the combined ContentForge pipeline.
    Accepts raw source text for end-to-end processing.
    """
    source_text: str = Field(
        ...,
        description="The raw plain text of the source document to process through the pipeline.",
        examples=[
            "Artificial intelligence is transforming healthcare. A recent pilot program analyzed 50,000 medical images over six months to assist doctors with diagnosis."
        ],
    )

    @field_validator("source_text")
    @classmethod
    def validate_source_text(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("source_text must not be empty or whitespace-only.")
        return value.strip()


class PipelineResponse(BaseModel):
    """
    Response model for the combined Agent 1 -> Agent 2 pipeline.
    Contains the validated outputs from both agents.
    """
    source_understanding: SourceUnderstanding = Field(
        ...,
        description="Structured source understanding generated by Agent 1.",
    )
    content_strategy: ContentStrategy = Field(
        ...,
        description="Multi-platform content strategy generated by Agent 2 using Agent 1's output.",
    )


class PipelineGenerationResponse(BaseModel):
    """
    Response model for the full Agent 1 -> Agent 2 -> Agent 3 pipeline.
    Contains the validated outputs from all three agents.
    """
    source_understanding: SourceUnderstanding = Field(
        ...,
        description="Structured source understanding generated by Agent 1.",
    )
    content_strategy: ContentStrategy = Field(
        ...,
        description="Multi-platform content strategy generated by Agent 2 using Agent 1's output.",
    )
    generated_content: GeneratedContent = Field(
        ...,
        description="Structured multi-platform content generated by Agent 3 using Agent 1 facts and Agent 2 strategy.",
    )
