from pydantic import BaseModel, Field, field_validator


class LLMTestRequest(BaseModel):
    message: str = Field(
        ...,
        description="The message prompt to send to the Groq LLM",
        examples=["Reply with exactly: ContentForge Groq connection successful."],
    )

    @field_validator("message")
    @classmethod
    def validate_message_not_empty(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("Message cannot be empty or contain only whitespace.")
        return value.strip()


class LLMTestResponse(BaseModel):
    response: str = Field(
        ...,
        description="Response generated by Groq LLM",
        examples=["ContentForge Groq connection successful."],
    )
